# Generated by Django 6.0.3 on 2026-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eligibility_criteria', models.JSONField()),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
