# Generated by Django 6.0.3 on 2026-03-12 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='letter',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='letter',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letter',
            name='hod_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_type',
            field=models.CharField(choices=[('bonafide', 'Bonafide Certificate'), ('noc', 'No Objection Certificate'), ('internship', 'Internship Permission'), ('academic', 'Academic Recommendation'), ('hackathon', 'Hackathon Permission'), ('other', 'Other')], default='bonafide', max_length=50),
        ),
        migrations.AddField(
            model_name='letter',
            name='principal_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='principal_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_approved_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letter',
            name='principal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='letter',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending HOD Approval'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('final_approved', 'Principal Approved'), ('final_rejected', 'Principal Rejected')], default='pending', max_length=20),
        ),
    ]
